version: '3.9'

services:
  products_categories:
    container_name: m4_sprint4-entrega
    image: m4_sprint4-entrega-pvillor
    build: .
    ports:
    - 3333:3333
    environment:
      - DB_USER=pvill
      - DB_HOST=db
      - DB=products_management
      - DB_PASSWORD=1234
      - DB_PORT=5432
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pvill
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=products_management
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pvill -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s